FROM ubuntu:20.04

RUN apt-get update &&\
    apt-get install -y\
        apt-transport-https\
        ca-certificates &&\
    sed -i 's/http:\/\/archive.ubuntu.com\/ubuntu/https:\/\/mirrors.ptisp.pt\/ubuntu/' /etc/apt/sources.list &&\
    sed -i 's/http:\/\/security.ubuntu.com\/ubuntu/https:\/\/mirrors.ptisp.pt\/ubuntu/' /etc/apt/sources.list &&\
    apt-get clean &&\
    rm -rf \
        /tmp/* \
        /var/tmp/*
