FROM ubuntu:focal

RUN apt-get update &&\
    apt-get install\
        apt-transport-https\
        ca-certificates &&\
    printf "deb https://mirrors.ptisp.pt/ubuntu/ focal main universe\ndeb-src https://mirrors.ptisp.pt/ubuntu/ focal main universe" >/etc/apt/sources.list &&\
    apt-get clean && \
    rm -rf \
        /tmp/* \
        /var/tmp/*
